/**
 * SUBCATEGORIES_MAP
 * Keys must exactly match the `name` field of each Category row in the DB.
 * Values are the subcategory strings stored in Product.subcategory.
 *
 * Structure mirrors BigHaat + Indian agri retail depth.
 * Every subcategory is specific enough to filter meaningfully.
 */
export const SUBCATEGORIES_MAP = {

  // ── 1. Seeds & Planting Material ─────────────────────────────────────────
  'Seeds & Planting Material': [
    // Field / Cereal Crops
    'Wheat Seeds',
    'Rice / Paddy Seeds',
    'Maize / Corn Seeds',
    'Jowar (Sorghum) Seeds',
    'Bajra (Pearl Millet) Seeds',
    'Ragi (Finger Millet) Seeds',
    'Barley Seeds',
    'Oat Seeds',
    // Pulses & Legumes
    'Soybean Seeds',
    'Chickpea / Chana Seeds',
    'Pigeon Pea / Tur Dal Seeds',
    'Moong / Green Gram Seeds',
    'Urad / Black Gram Seeds',
    'Lentil / Masoor Seeds',
    'Groundnut / Peanut Seeds',
    'Cowpea Seeds',
    'Horse Gram Seeds',
    // Oilseeds
    'Mustard / Rapeseed Seeds',
    'Sunflower Seeds',
    'Sesame / Til Seeds',
    'Castor Seeds',
    'Linseed / Flaxseed Seeds',
    'Safflower Seeds',
    // Cash Crops
    'Cotton Seeds',
    'Sugarcane Sets / Setts',
    'Tobacco Seeds',
    'Jute Seeds',
    // Vegetables
    'Tomato Seeds',
    'Onion Seeds / Sets',
    'Potato Seeds / Mini Tubers',
    'Brinjal / Eggplant Seeds',
    'Chilli / Pepper Seeds',
    'Capsicum / Bell Pepper Seeds',
    'Cauliflower Seeds',
    'Cabbage Seeds',
    'Broccoli Seeds',
    'Cucumber Seeds',
    'Bitter Gourd / Karela Seeds',
    'Bottle Gourd / Lauki Seeds',
    'Ridge Gourd / Turai Seeds',
    'Snake Gourd Seeds',
    'Pumpkin / Kaddu Seeds',
    'Watermelon Seeds',
    'Muskmelon / Kharbooja Seeds',
    'Lady Finger / Okra Seeds',
    'Peas Seeds',
    'Beans / Cluster Beans Seeds',
    'Spinach / Palak Seeds',
    'Fenugreek / Methi Seeds',
    'Radish Seeds',
    'Carrot Seeds',
    'Beetroot Seeds',
    'Turnip Seeds',
    'Sweet Corn Seeds',
    'Baby Corn Seeds',
    'Lettuce & Salad Greens Seeds',
    'Celery Seeds',
    'Leek Seeds',
    // Fruits / Saplings
    'Mango Saplings',
    'Banana Tissue Culture Plants',
    'Papaya Seeds / Plants',
    'Guava Saplings',
    'Pomegranate Saplings',
    'Lemon / Citrus Saplings',
    'Grape Cuttings / Saplings',
    'Strawberry Runners',
    'Fig Saplings',
    'Sapota / Chikoo Saplings',
    'Custard Apple Saplings',
    'Dragon Fruit Plants',
    'Avocado Saplings',
    // Spices & Condiments
    'Turmeric Rhizomes',
    'Ginger Rhizomes',
    'Garlic Cloves / Sets',
    'Coriander Seeds',
    'Cumin / Jeera Seeds',
    'Fennel / Saunf Seeds',
    'Ajwain Seeds',
    'Black Pepper Cuttings',
    'Cardamom Plants',
    // Flowers
    'Marigold Seeds',
    'Rose Cuttings / Saplings',
    'Chrysanthemum Cuttings',
    'Jasmine Cuttings',
    'Tuberose Bulbs',
    'Gladiolus Corms',
    'Sunflower (Ornamental) Seeds',
    'Zinnia Seeds',
    'Aster Seeds',
    // Medicinal & Aromatic
    'Aloe Vera Suckers',
    'Tulsi / Basil Seeds',
    'Stevia Cuttings',
    'Ashwagandha Seeds',
    'Brahmi / Bacopa Plants',
    'Lemongrass Slips',
    'Mint / Pudina Cuttings',
    // Fodder & Forage
    'Napier Grass Slips',
    'Lucerne / Alfalfa Seeds',
    'Hybrid Napier Seeds',
    'Cowpea Fodder Seeds',
    'Sorghum Fodder Seeds',
    // Nursery & Plantation
    'Coconut Seedlings',
    'Areca Nut Seedlings',
    'Cashew Grafts',
    'Teak / Sagwan Saplings',
    'Eucalyptus Saplings',
    'Bamboo Rhizomes',
    // Specialty
    'Mushroom Spawn (Oyster)',
    'Mushroom Spawn (Button)',
    'Mushroom Spawn (Milky / Paddy Straw)',
    'Microgreens Seeds',
    'Sprout Seeds (Mung, Fenugreek)',
    'Hydroponics / Aeroponics Seeds',
  ],

  // ── 2. Fertilizers & Soil Nutrition ────────────────────────────────────────
  'Fertilizers & Soil Nutrition': [
    // Straight Fertilizers (N, P, K)
    'Urea (46% N)',
    'DAP — Di-Ammonium Phosphate',
    'MOP — Muriate of Potash',
    'SOP — Sulphate of Potash',
    'SSP — Single Super Phosphate',
    'TSP — Triple Super Phosphate',
    'Ammonium Sulphate',
    'Calcium Ammonium Nitrate (CAN)',
    // Complex / Compound Fertilizers
    'NPK 10-26-26',
    'NPK 12-32-16',
    'NPK 19-19-19',
    'NPK 20-20-0',
    'NPK 17-17-17',
    'NPK 13-40-13',
    'NPK 0-52-34',
    // Water Soluble Fertilizers
    'Water Soluble NPK Grades',
    'Calcium Nitrate (Water Soluble)',
    'Potassium Nitrate',
    'Potassium Schoenite',
    'MAP — Mono Ammonium Phosphate',
    'MKP — Mono Potassium Phosphate',
    // Organic Fertilizers
    'Vermicompost',
    'FYM — Farm Yard Manure',
    'Neem Cake',
    'Castor Cake',
    'Pongamia / Karanj Cake',
    'Fish Meal',
    'Bone Meal',
    'Blood Meal',
    'Seaweed Extract / Granules',
    'Humic Acid',
    'Fulvic Acid',
    'Amino Acid Fertilizers',
    // Bio-Fertilizers
    'Rhizobium (for Legumes)',
    'Azospirillum',
    'Azotobacter',
    'PSB — Phosphate Solubilising Bacteria',
    'KMB — Potassium Mobilising Bacteria',
    'Mycorrhiza / VAM',
    'Trichoderma (Soil Application)',
    'Combined Bio-Fertilizer Consortia',
    // Soil Amendments & Conditioners
    'Gypsum / Calcium Sulphate',
    'Agricultural Lime',
    'Dolomite',
    'Bentonite',
    'Soil Wetting Agents',
    'pH Correctors (Acid / Alkaline Soil)',
    'Zeolite',
    'Biochar',
    'Compost Activators',
  ],

  // ── 3. Crop Protection ──────────────────────────────────────────────────────
  'Crop Protection': [
    // Insecticides
    'Organophosphate Insecticides',
    'Pyrethroid Insecticides',
    'Neonicotinoid Insecticides',
    'Carbamate Insecticides',
    'Chloronicotinyl Insecticides',
    'Diamide / Rynaxypyr Insecticides',
    'Spinosad / Bio-Insecticides',
    'IGR — Insect Growth Regulators',
    'Systemic Insecticides',
    'Contact Insecticides',
    // Fungicides
    'Broad Spectrum Fungicides',
    'Copper-based Fungicides',
    'Triazole Fungicides',
    'Strobilurin Fungicides',
    'Benzimidazole Fungicides',
    'Mancozeb / Dithiocarbamate Fungicides',
    'Bio-Fungicides (Trichoderma, Pseudomonas)',
    'Seed Treatment Fungicides',
    // Herbicides / Weedicides
    'Pre-Emergence Herbicides',
    'Post-Emergence Herbicides',
    'Selective Herbicides',
    'Non-Selective / Total Herbicides',
    'Grass Weedicides',
    'Broadleaf Weedicides',
    'Soil Sterilants',
    // Other Pest Control
    'Rodenticides (Rat / Mouse Control)',
    'Nematicides',
    'Molluscicides (Snail & Slug Control)',
    'Termiticides',
    'Acaricides / Miticides',
    // Trap & Lure Systems
    'Pheromone Traps & Lures',
    'Yellow Sticky Traps',
    'Blue Sticky Traps',
    'Light / UV Traps',
    'Delta / Water Traps',
    // Adjuvants & Additives
    'Stickers & Spreaders',
    'Penetrants & Activators',
    'Anti-Drift Agents',
    'Buffering Agents',
    // Bactericides
    'Copper-based Bactericides',
    'Antibiotic-based Bactericides',
    // Defoliants & Desiccants
    'Defoliants',
    'Desiccants',
  ],

  // ── 4. Organic & Natural Farming ────────────────────────────────────────────
  'Organic & Natural Farming': [
    // Bio-Pesticides
    'Neem-based Products (Neem Oil, Neem EC)',
    'Bt (Bacillus thuringiensis) Biopesticides',
    'Beauveria bassiana',
    'Metarhizium anisopliae',
    'NPV (Nucleopolyhedrovirus)',
    'Verticillium lecanii',
    'Pseudomonas fluorescens',
    // Natural Pest Management
    'Garlic Extract',
    'Chilli Extract',
    'Fermented Buttermilk-based Products',
    'Panchagavya',
    'Beejamrutha / Jivamrutha Inputs',
    // Organic Compost & Manures
    'Vermicompost (Certified Organic)',
    'PROM — Phosphate Rich Organic Manure',
    'Organic NPK Granules',
    'Green Manure Seeds (Dhaincha, Sesbania)',
    'Composted Coir Pith',
    // Certified Organic Products
    'NPOP / NOP Certified Inputs',
    'PGS-India Certified Products',
    // Composting Equipment & Accelerators
    'Compost Bins & Tumblers',
    'Vermicompost Beds',
    'Composting Accelerator Cultures',
    'Compost Thermometers',
  ],

  // ── 5. Plant Growth Regulators ───────────────────────────────────────────────
  'Plant Growth Regulators': [
    'Gibberellic Acid (GA3)',
    'Ethephon / Ethylene Generators',
    'Cytokinin-based Regulators (BAP, Kinetin)',
    'Auxin-based Products (NAA, IAA, IBA)',
    'Paclobutrazol (Cultar)',
    'Mepiquat Chloride',
    'Triacontanol',
    'Brassinolide / Brassinosteroids',
    'Salicylic Acid',
    'Humic + Fulvic Acid Stimulants',
    'Seaweed Growth Stimulants',
    'Amino Acid-based Stimulants',
    'Rooting Hormones (IBA Powders)',
    'Anti-Stress / Crop Reviver Products',
    'Flowering & Fruiting Boosters',
    'Fruit Size Enhancers',
    'Dormancy Breakers',
  ],

  // ── 6. Irrigation & Water Management ─────────────────────────────────────────
  'Irrigation & Water Management': [
    // Drip Systems
    'Drip Irrigation Complete Systems',
    'Inline Drip Laterals',
    'Online Drippers & Emitters',
    'Drip Tape',
    'Pressure Compensating (PC) Drippers',
    'Micro Tubes & Arrow Drippers',
    // Sprinkler Systems
    'Sprinkler System Complete Sets',
    'Micro Sprinklers',
    'Rotating / Impact Sprinklers',
    'Wobbler Sprinklers',
    'Overhead Rain-Gun',
    // Fogger & Mist
    'Fogger / Mist Nozzles (Greenhouse)',
    'Anti-Drip Fogger Assemblies',
    // Pipes & Fittings
    'HDPE Pipes (Various Diameters)',
    'PVC Pipes',
    'LLDPE Laterals',
    'Couplers, Tees & Elbows',
    'Grommet Fittings',
    'Filters (Disc / Screen / Sand)',
    'Venturi Injectors',
    'Pressure Regulators & Gauges',
    'Flush Valves',
    // Pumps
    'Centrifugal Water Pumps',
    'Submersible Pumps',
    'Solar Pumps',
    'Diesel Pumps',
    'Monoblock Pumps',
    'Hand Pumps',
    // Storage
    'Water Storage Tanks (HDPE / FRP)',
    'Farm Ponds / Liners',
    'Overhead Tank Stands',
    // Fertigation
    'Fertigation Tanks & Injectors',
    'Fertigation Controllers',
    'EC / pH Monitoring Kits',
    // Automation
    'Irrigation Timers & Controllers',
    'Solenoid Valves',
    'Smart Irrigation Controllers (IoT)',
  ],

  // ── 7. Farm Machinery & Equipment ──────────────────────────────────────────
  'Farm Machinery & Equipment': [
    // Tillage
    'Power Tillers',
    'Rotavators / Rotary Tillers',
    'Disc Harrows',
    'Cultivators',
    'Reversible Ploughs',
    'Subsoilers',
    'Laser Land Levellers',
    // Sowing & Planting
    'Seed Drills (Manual / Power)',
    'Dibbling Tools & Planters',
    'Transplanting Machines (Paddy, Vegetable)',
    'Potato Planters',
    'Sugarcane Planters',
    'Zero-Till Ferti-Seed Drills',
    // Harvesting
    'Reapers & Combine Harvesters',
    'Maize Harvesters',
    'Groundnut Diggers',
    'Root Vegetable Harvesters',
    'Combine Harvester Attachments',
    // Threshing & Processing
    'Grain Threshers (Multi-crop)',
    'Paddy Threshers',
    'Maize Shellers',
    'Groundnut Shellers',
    'Winnowing Machines',
    // Crop Management
    'Power Weeders',
    'Inter-Cultivation Equipment',
    'Ridge & Furrow Makers',
    // Post-Harvest Processing
    'Sorting & Grading Machines',
    'Destoners',
    'Dewatering Equipment',
    'Oil Expellers',
    // Transport
    'Tractor Trolleys & Trailers',
    'Mini Trucks / Power Vehicles',
    'Wheel Barrows',
    // Miscellaneous
    'Tractors & Power Sources',
    'Spare Parts & Attachments',
  ],

  // ── 8. Hand Tools & Small Equipment ────────────────────────────────────────
  'Hand Tools & Small Equipment': [
    // Digging & Tillage
    'Spades & Shovels',
    'Forks (Garden / Manure)',
    'Hoes & Khurpis',
    'Hand Cultivators',
    'Trowels',
    'Hand Rakes',
    // Cutting
    'Pruning Shears / Secateurs',
    'Hedge Shears',
    'Loppers',
    'Garden Saws',
    'Sickles & Grass Cutters',
    'Grafting & Budding Knives',
    'Fruit Pickers',
    // Watering
    'Watering Cans',
    'Garden Hoses & Nozzles',
    'Manual Knapsack Sprayers',
    'Battery-operated Knapsack Sprayers',
    'Hand-Compression Sprayers',
    // Carrying & Lifting
    'Baskets & Crates',
    'Head Baskets',
    'Farm Buckets & Tubs',
    // Staking, Tying & Support
    'Bamboo Stakes',
    'Iron / GI Stakes',
    'Plant Ties & Clips',
    'Tomato Spirals',
    'Trellis Nets',
    // Measuring
    'Soil pH Meters',
    'Soil Moisture Meters',
    'EC / TDS Meters',
    'Thermometers (Soil / Air)',
    'Rain Gauges',
    'Weighing Scales (Farm Use)',
    // Other
    'Knapsack Batteries & Accessories',
    'Sharpening Tools',
  ],

  // ── 9. Protected Cultivation ────────────────────────────────────────────────
  'Protected Cultivation': [
    // Polyhouse / Greenhouse
    'Polyhouse Film & Plastic Sheets',
    'GI / Galvanised Frames',
    'Polyhouse Structure (Complete Set)',
    'Ventilation Fans & Cooling Pads',
    'Thermostat & Humidity Controllers',
    // Shade Nets
    'Shade Net (50% Shade)',
    'Shade Net (75% Shade)',
    'Shade Net (35% Shade)',
    'Insect Proof Nets',
    // Mulching
    'Black Plastic Mulch Film',
    'Silver-Black Mulch Film',
    'Biodegradable Mulch',
    'Organic Mulch (Straw, Coir)',
    // Support Structures
    'Bamboo Trellises',
    'GI Wire & Posts',
    'Trellis Netting',
    'Tomato / Cucumber Wire',
    // Nursery
    'Nursery Trays (Pro Trays)',
    'Coco Peat Blocks',
    'Jiffy / Peat Pellets',
    'Nursery Bags & Poly Bags',
    'Root Trainer Cells',
    // Hydroponics
    'Hydroponic NFT Systems',
    'Grow Bags & Substrate',
    'Coco Coir Slabs',
    'Growing Media (Perlite, Vermiculite, LECA)',
    'Hydroponic Nutrient Solutions',
    'DWC / Raft Systems',
    'Grow Lights (LED)',
  ],

  // ── 10. Micronutrients & Specialty Nutrition ───────────────────────────────
  'Micronutrients & Specialty Nutrition': [
    'Zinc Sulphate',
    'Ferrous Sulphate / Iron EDTA Chelate',
    'Boron (Solubor / Borax)',
    'Manganese Sulphate',
    'Copper Sulphate',
    'Molybdenum',
    'Magnesium Sulphate (Epsom Salt)',
    'Calcium Nitrate (Foliar)',
    'Sulphur (Wettable / Dusting)',
    'Multi-Micronutrient Mixtures',
    'EDTA Chelated Micronutrients',
    'Silica / Silicon Products',
    'Cobalt Products',
    'Foliar Nutrition Combinations',
    'Calcium + Boron Combos (Fruit Quality)',
  ],

  // ── 11. Seeds Treatment & Additives ────────────────────────────────────────
  'Seeds Treatment & Additives': [
    'Thiram-based Seed Treatment Fungicides',
    'Carbendazim Seed Treatment',
    'Imidacloprid Seed Treatment Insecticides',
    'Thiamethoxam Seed Treatment',
    'Metalaxyl + Mancozeb Seed Treatment',
    'Trichoderma (Seed Treatment)',
    'Rhizobium Seed Inoculants',
    'Azospirillum Seed Inoculants',
    'PSB Seed Inoculants',
    'Combined Seed Treatment Kits',
    'Seed Priming Chemicals',
    'Polymer / Film Coatings for Seeds',
    'Coloured Seed Dyes / Markers',
    'Germination Boosters',
  ],

  // ── 12. Livestock, Dairy & Poultry ─────────────────────────────────────────
  'Livestock, Dairy & Poultry': [
    // Cattle & Buffalo
    'Cattle Feed & Concentrates',
    'Bypass Protein Feed',
    'Mineral Mixture (Cattle)',
    'Green Fodder Choppers',
    'Chaff Cutters',
    'Feeding Troughs & Mangers',
    'Milking Equipment (Manual / Electric)',
    'Milk Can & Storage',
    'Cattle Health Products (Dewormer, Vitamins)',
    'Ear Tags & ID Equipment',
    // Goat & Sheep
    'Goat / Sheep Feed',
    'Mineral Blocks for Small Ruminants',
    'Drenching Guns',
    'Shearing Scissors',
    // Poultry
    'Layer / Broiler Feed',
    'Chick Starter Feed',
    'Poultry Feeders & Drinkers',
    'Brooding Equipment',
    'Egg Trays & Handling Equipment',
    'Poultry Vaccines & Health Products',
    'Cages & Netting',
    // Beekeeping
    'Bee Boxes & Hive Equipment',
    'Bee Suits & Gloves',
    'Honey Extractors',
    'Queen Rearing Equipment',
    // Sericulture
    'Silkworm Rearing Trays',
    'Mulberry Cultivation Inputs',
    // General Animal Health
    'Deworming Medicines',
    'Vitamin & Mineral Supplements',
    'Wound Care & Antiseptics',
    'Teat Dips & Mastitis Care',
  ],

  // ── 13. Fencing & Farm Protection ──────────────────────────────────────────
  'Fencing & Farm Protection': [
    'Barbed Wire',
    'GI Wire (Plain)',
    'Chain-Link Fencing',
    'Welded Mesh Fencing',
    'Electric Fence Energisers',
    'Electric Fence Wire & Tape',
    'Solar Electric Fence Systems',
    'Bird Netting',
    'Anti-Hail Nets',
    'Tree Guards',
    'Fence Posts (GI / Concrete)',
    'Farm Gates & Latches',
    'Strain Insulators & Accessories',
    'Reflective Bird Scarer Tape',
    'Ultrasonic Animal Repellers',
    'Rodent Glue Boards',
  ],

  // ── 14. Storage & Packaging ─────────────────────────────────────────────────
  'Storage & Packaging': [
    'HDPE Woven Sacks / Bags',
    'Jute Bags',
    'PP / BOPP Packaging Bags',
    'Ventilated Plastic Crates',
    'Wooden Crates & Pallets',
    'Grain Storage Bins (HDPE / Metal)',
    'Hermetic Storage Bags (PICS / ZeroFly)',
    'Grain Moisture Meters',
    'Silica Gel Desiccants',
    'Fumigation Products (Aluminium Phosphide)',
    'Cool-Packs & Cold Storage Liners',
    'Stretch Wrap & Cling Film',
    'Bubble Wrap & Foam Nets (Fruit)',
    'Corrugated Boxes',
    'Mango / Fruit Export Boxes',
    'Weighing & Labelling Equipment',
  ],

  // ── 15. Agri Technology & Smart Farming ─────────────────────────────────────
  'Agri Technology & Smart Farming': [
    'Agriculture Drones (Spraying)',
    'Drone Batteries & Accessories',
    'Soil Testing Kits (NPK, pH)',
    'Digital Soil Testing Devices',
    'Weather Stations (Farm Level)',
    'Leaf Area Meters',
    'Plant Disease Detection Apps / Devices',
    'IoT Soil Moisture Sensors',
    'IoT Weather Sensors',
    'Remote Monitoring Systems',
    'GPS Trackers for Farm Equipment',
    'Variable Rate Application Controllers',
    'Data Loggers',
    'Crop Monitoring NDVI Tools',
    'Automated Irrigation Controllers',
  ],

  // ── 16. Solar & Energy ──────────────────────────────────────────────────────
  'Solar & Energy': [
    'Solar Water Pumps',
    'Solar Panels (For Farm Use)',
    'Solar Pump Controllers / Inverters',
    'Solar Fencing Energisers',
    'Solar Lights (Farm / Pathway)',
    'Battery Banks',
    'Portable Generators (Petrol / Diesel)',
    'Biogas Plant Kits',
    'Solar Dryers',
    'Solar Cold Storage Units',
  ],

  // ── 17. Safety & Protective Gear ────────────────────────────────────────────
  'Safety & Protective Gear': [
    'Chemical Resistant Gloves',
    'Nitrile Gloves',
    'Face Shields',
    'Safety Goggles',
    'Respirators & Dust Masks',
    'Chemical Resistant Aprons',
    'Protective Coveralls / Suits',
    'Safety Boots & Gumboots',
    'Hard Hats',
    'First Aid Kits (Field)',
    'Eye Wash Stations',
    'Decontamination Kits',
    'Warning Signs & Safety Labels',
    'Anti-Fatigue Mats',
  ],

  // ── 18. Spraying Equipment ────────────────────────────────────────────────────
  'Spraying Equipment': [
    'Manual Knapsack Sprayer (16L)',
    'Battery Knapsack Sprayer',
    'Electric / Motorised Sprayer',
    'Petrol / Engine Sprayer',
    'Trolley / Wheel Sprayer',
    'Mist Blower (Motorised)',
    'Boom Sprayer (Tractor Mounted)',
    'Electrostatic Sprayer',
    'Drone Sprayers',
    'Sprayer Nozzles (Flat Fan, Hollow Cone)',
    'Sprayer Tanks',
    'Sprayer Pumps & Diaphragms',
    'Spray Wands & Lances',
    'Anti-Drip Check Valves',
    'Sprayer Maintenance Kits',
  ],

  // ── 19. Harvesting & Post-Harvest ────────────────────────────────────────────
  'Harvesting & Post-Harvest': [
    'Sickles & Scythes',
    'Harvesting Knives & Shears',
    'Fruit Harvesting Poles',
    'Mango / Fruit Pluckers',
    'Vegetable Harvesting Crates',
    'Paddy / Wheat Harvesters (Small)',
    'Cleaning & Washing Units',
    'Sorting Belts',
    'Grading Trays & Sizers',
    'Destoners & Dewatering Units',
    'Slicers, Cutters & Dicers',
    'Cold Storage Accessories',
    'Pre-Cooling Units',
    'Ripening Chambers',
    'Waxing Machines',
    'Weighing Machines & Balances',
    'Packing Tables',
  ],

  // ── 20. Aquaculture & Fisheries ───────────────────────────────────────────────
  'Aquaculture & Fisheries': [
    'Fish Feed (Pellets)',
    'Shrimp Feed',
    'Pond Aerators',
    'Water Quality Testing Kits',
    'Fish Nets',
    'Cages (Cage Culture)',
    'Hapa Nets',
    'HDPE Ponds',
    'Biofloc Culture Kits',
    'Probiotics for Aquaculture',
    'Disease Management Products',
    'Fishing Equipment (Rods, Reels)',
    'Weighing Scales (Wet Market)',
  ],

  // ── 21. Horticulture & Nursery ────────────────────────────────────────────────
  'Horticulture & Nursery': [
    'Budding & Grafting Supplies',
    'Plant Labels & Tags',
    'Propagation Mats (Heat)',
    'Grow Bags (Black HDPE)',
    'Terracotta & Ceramic Pots',
    'Decorative Planter Sets',
    'Hanging Baskets',
    'Moss Poles & Coconut Coir Poles',
    'Orchid Mounts & Media',
    'Bonsai Tools & Media',
    'Rooting Cubes & Plugs',
    'Nutrient Solution (Horticulture)',
    'Fruiting Bags (Mushroom Cultivation)',
    'Landscape Fabric / Weed Barrier',
    'Garden Décor & Signage',
  ],

  // ── 22. Agri Inputs for Home & Kitchen Garden ─────────────────────────────
  'Agri Inputs for Home & Kitchen Garden': [
    'Kitchen Garden Seed Kits',
    'Terrace Garden Kits',
    'Balcony Garden Pots & Trays',
    'Potting Mix & Garden Soil',
    'Coco Peat (Small Pack)',
    'Slow Release Fertilizer Sticks',
    'Organic Liquid Fertilizer (Small)',
    'Neem Oil (Small Pack)',
    'Insect Traps (Home Garden)',
    'Mini Drip Kits',
    'Watering Cans (Small)',
    'Mini Sprayers',
    'Garden Gloves',
    'Herb Growing Kits',
    'Compost Bins (Small)',
    'Worm Composting Kits',
    'Grow Bags (Home Size)',
  ],
};
